/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Benh;
import Model.ThemThuoc;
import Model.ToaThuoc;
import Model2.BenhNhan;
import Model2.HoaDon;
import Model2.PhieuKham;
import Model3.BaoCaoDoanhThu;
import Model3.BaoCaoThuoc;
import Model3.NguoiDung;
import Model3.TraCuu;
import Model4.HDSD;
import Model4.ThongTin;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author Maid
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon("src/Imagi/NEN.png");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            } };
            jMenuBar1 = new javax.swing.JMenuBar();
            jMenu2 = new javax.swing.JMenu();
            jMenuQLNguoiDung = new javax.swing.JMenuItem();
            jMenuBCSDThuoc = new javax.swing.JMenuItem();
            jMenuBCDoanhThu = new javax.swing.JMenuItem();
            jMenuTraCuu = new javax.swing.JMenuItem();
            jMenu1 = new javax.swing.JMenu();
            jMenuBenhNhan = new javax.swing.JMenuItem();
            jMenuPhieuKham = new javax.swing.JMenuItem();
            jMenuHoaDon = new javax.swing.JMenuItem();
            jMenu3 = new javax.swing.JMenu();
            jMenuThuoc = new javax.swing.JMenuItem();
            jMenuBenh = new javax.swing.JMenuItem();
            jMenuToạThuoc = new javax.swing.JMenuItem();
            jMenu5 = new javax.swing.JMenu();
            jMenu4 = new javax.swing.JMenu();
            jMenuHDSD = new javax.swing.JMenuItem();
            jMenuThongTin = new javax.swing.JMenuItem();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setTitle("QUẢN LÝ PHÒNG MẠCH TƯ");

            jPanel1.setBackground(new java.awt.Color(255, 255, 255));
            jPanel1.setToolTipText("");
            jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 712, Short.MAX_VALUE)
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 511, Short.MAX_VALUE)
            );

            jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

            javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
            jDesktopPane1.setLayout(jDesktopPane1Layout);
            jDesktopPane1Layout.setHorizontalGroup(
                jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            jDesktopPane1Layout.setVerticalGroup(
                jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane1)
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane1)
            );

            jMenu2.setText("Quản Lý Người Dùng");
            jMenu2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenu2ActionPerformed(evt);
                }
            });

            jMenuQLNguoiDung.setText("Quản Lý Người Dùng");
            jMenuQLNguoiDung.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuQLNguoiDungActionPerformed(evt);
                }
            });
            jMenu2.add(jMenuQLNguoiDung);

            jMenuBCSDThuoc.setText("Báo Cáo Sử Dụng Thuốc");
            jMenuBCSDThuoc.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuBCSDThuocActionPerformed(evt);
                }
            });
            jMenu2.add(jMenuBCSDThuoc);

            jMenuBCDoanhThu.setText("Báo Cáo Doanh Thu");
            jMenuBCDoanhThu.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuBCDoanhThuActionPerformed(evt);
                }
            });
            jMenu2.add(jMenuBCDoanhThu);

            jMenuTraCuu.setText("Tra Cứu Bệnh Nhân");
            jMenuTraCuu.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuTraCuuActionPerformed(evt);
                }
            });
            jMenu2.add(jMenuTraCuu);

            jMenuBar1.add(jMenu2);

            jMenu1.setText("Quản Lý Bệnh Nhân");

            jMenuBenhNhan.setText("Bệnh Nhân");
            jMenuBenhNhan.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuBenhNhanActionPerformed(evt);
                }
            });
            jMenu1.add(jMenuBenhNhan);

            jMenuPhieuKham.setText("Phiếu Khám ");
            jMenuPhieuKham.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuPhieuKhamActionPerformed(evt);
                }
            });
            jMenu1.add(jMenuPhieuKham);

            jMenuHoaDon.setText("Hóa Đơn Thanh Toán");
            jMenuHoaDon.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuHoaDonActionPerformed(evt);
                }
            });
            jMenu1.add(jMenuHoaDon);

            jMenuBar1.add(jMenu1);

            jMenu3.setText("Quản Lý Thông Tin");

            jMenuThuoc.setText("Thuốc");
            jMenuThuoc.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuThuocActionPerformed(evt);
                }
            });
            jMenu3.add(jMenuThuoc);

            jMenuBenh.setText("Bệnh");
            jMenuBenh.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuBenhActionPerformed(evt);
                }
            });
            jMenu3.add(jMenuBenh);

            jMenuToạThuoc.setText("Toa Thuốc");
            jMenuToạThuoc.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuToạThuocActionPerformed(evt);
                }
            });
            jMenu3.add(jMenuToạThuoc);

            jMenuBar1.add(jMenu3);

            jMenu5.setText("Cập Nhập Thông Tin");
            jMenuBar1.add(jMenu5);

            jMenu4.setText("Thông Tin Phần Mềm");

            jMenuHDSD.setText("HD Sử Dụng");
            jMenuHDSD.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuHDSDActionPerformed(evt);
                }
            });
            jMenu4.add(jMenuHDSD);

            jMenuThongTin.setText("Thông Tin Phát Triển");
            jMenuThongTin.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuThongTinActionPerformed(evt);
                }
            });
            jMenu4.add(jMenuThongTin);

            jMenuBar1.add(jMenu4);

            setJMenuBar(jMenuBar1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jMenuBCSDThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBCSDThuocActionPerformed
        // TODO add your handling code here:
        BaoCaoThuoc BCT = new BaoCaoThuoc();
        BCT.setVisible(true);
    }//GEN-LAST:event_jMenuBCSDThuocActionPerformed

    private void jMenuQLNguoiDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuQLNguoiDungActionPerformed
        // TODO add your handling code here:
        NguoiDung ND = new NguoiDung();
        ND.setVisible(true);
        
    }//GEN-LAST:event_jMenuQLNguoiDungActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuBCDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBCDoanhThuActionPerformed
        // TODO add your handling code here:
        BaoCaoDoanhThu BCDT = new BaoCaoDoanhThu();
        BCDT.setVisible(true);
    }//GEN-LAST:event_jMenuBCDoanhThuActionPerformed

    private void jMenuTraCuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTraCuuActionPerformed
        // TODO add your handling code here:
        TraCuu TC = new TraCuu();
        TC.setVisible(true);
    }//GEN-LAST:event_jMenuTraCuuActionPerformed

    private void jMenuBenhNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBenhNhanActionPerformed
        // TODO add your handling code here:
        BenhNhan BN = new BenhNhan();
        BN.setVisible(true);
    }//GEN-LAST:event_jMenuBenhNhanActionPerformed

    private void jMenuPhieuKhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPhieuKhamActionPerformed
        // TODO add your handling code here:
        PhieuKham PK = new PhieuKham();
        PK.setVisible(true);
    }//GEN-LAST:event_jMenuPhieuKhamActionPerformed

    private void jMenuHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHoaDonActionPerformed
        // TODO add your handling code here:
        HoaDon HD = new HoaDon();
        HD.setVisible(true);
    }//GEN-LAST:event_jMenuHoaDonActionPerformed

    private void jMenuBenhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBenhActionPerformed
        // TODO add your handling code here:
        Benh B = new Benh();
        B.setVisible(true);
    }//GEN-LAST:event_jMenuBenhActionPerformed

    private void jMenuToạThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuToạThuocActionPerformed
        // TODO add your handling code here:
        ToaThuoc TT = new ToaThuoc();
        TT.setVisible(true);
        jPanel2.add(TT);
    }//GEN-LAST:event_jMenuToạThuocActionPerformed

    private void jMenuHDSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHDSDActionPerformed
        // TODO add your handling code here:
        HDSD HD = new HDSD();
        HD.setVisible(true);
    }//GEN-LAST:event_jMenuHDSDActionPerformed

    private void jMenuThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuThongTinActionPerformed
        // TODO add your handling code here:
        ThongTin TTT = new ThongTin();
        TTT.setVisible(true);
    }//GEN-LAST:event_jMenuThongTinActionPerformed

    private void jMenuThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuThuocActionPerformed
        // TODO add your handling code here:
        ThemThuoc T;
        T = new ThemThuoc();
        T.setVisible(true);
        jPanel2.add(T);
    }//GEN-LAST:event_jMenuThuocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuBCDoanhThu;
    private javax.swing.JMenuItem jMenuBCSDThuoc;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuBenh;
    private javax.swing.JMenuItem jMenuBenhNhan;
    private javax.swing.JMenuItem jMenuHDSD;
    private javax.swing.JMenuItem jMenuHoaDon;
    private javax.swing.JMenuItem jMenuPhieuKham;
    private javax.swing.JMenuItem jMenuQLNguoiDung;
    private javax.swing.JMenuItem jMenuThongTin;
    private javax.swing.JMenuItem jMenuThuoc;
    private javax.swing.JMenuItem jMenuToạThuoc;
    private javax.swing.JMenuItem jMenuTraCuu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
